name: Linters

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

env:
  FORCE_COLOR: 1
  NODE_VERSION: "20.x"

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx --config eslint.config.js --max-warnings=0

  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}" --max-warnings=0

  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then
            echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."
            echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future."
            exit 1
          fi